# Generated by Django 3.2.6 on 2021-09-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_keyword_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='update',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
