# Generated by Django 3.2.6 on 2021-09-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20210909_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
